# -*- coding: utf-8 -*-
"""Primeiro projeto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JQhW8UBXi0AVIeJTIwwiuOKNHA9WGGTQ
"""

dado78 = input ('dado')
dado79 = input ('dado')
dado80 = input ('dado')
dado81 = input ('dado')
dado82 = input ('dado')

dado78 = int(input ('78'))
dado79 = int(input ('79'))
dado80 = int(input ('80'))
dado81 = int(input ('81'))
dado82 = int(input ('82'))

dado78 + dado80
print (dado78 + dado80)

dado82 - dado78
print(dado82 - dado78)

dado80 * dado78
print(dado80 * dado78)

dado80 / dado80
print(dado80 / dado80)

dado78 = 78
dado79 = 79
dado80 = 80
dado81 = 81
dado82 = 82

if dado78 < dado80:
  print ('dado78 está abaixo de dado80')
elif dado78 > dado80:
  print ('dado78 está acima de dado80')

for dado78 in range (dado78, dado82):
  print (dado78)